/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		ElButton: (typeof import('element-plus/es'))['ElButton']
		ElCol: (typeof import('element-plus/es'))['ElCol']
		ElForm: (typeof import('element-plus/es'))['ElForm']
		ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
		ElInput: (typeof import('element-plus/es'))['ElInput']
		RouterLink: (typeof import('vue-router'))['RouterLink']
		RouterView: (typeof import('vue-router'))['RouterView']
		Verify: (typeof import('./src/components/verifition/Verify.vue'))['default']
		VerifyPoints: (typeof import('./src/components/verifition/Verify/VerifyPoints.vue'))['default']
		VerifySlide: (typeof import('./src/components/verifition/Verify/VerifySlide.vue'))['default']
	}
}
