/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		copy: (typeof import('./src/components/verifition/Verify/VerifyPoints copy.vue'))['default']
		ElButton: (typeof import('element-plus/es'))['ElButton']
		ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
		ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup']
		ElCol: (typeof import('element-plus/es'))['ElCol']
		ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
		ElForm: (typeof import('element-plus/es'))['ElForm']
		ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
		ElInput: (typeof import('element-plus/es'))['ElInput']
		ElOption: (typeof import('element-plus/es'))['ElOption']
		ElRadio: (typeof import('element-plus/es'))['ElRadio']
		ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
		ElSelect: (typeof import('element-plus/es'))['ElSelect']
		ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
		ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker']
		HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
		RouterLink: (typeof import('vue-router'))['RouterLink']
		RouterView: (typeof import('vue-router'))['RouterView']
		Verify: (typeof import('./src/components/verifition/Verify.vue'))['default']
		VerifyPoints: (typeof import('./src/components/verifition/Verify/VerifyPoints.vue'))['default']
		VerifySlide: (typeof import('./src/components/verifition/Verify/VerifySlide.vue'))['default']
	}
}
